### ISSUE TITLE
Rename or remove fromText and toText

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/prolude#13]
Turns out we want to define a lot of functions named `fromText` and `toText`. For example:

``` hs
module Name (Name, fromText, toText) where

import Data.Text (Text)

newtype Name = Name Text deriving (Eq, Show)

fromText :: Text -> Name
fromText = Name

toText :: Name -> Text
toText (Name text) = text
```

I think we should either rename these functions or remove them. If we rename them, I propose `textToString` for `fromText` and `stringToText` for `toText`. That way it's clear which types are at both ends of the conversion.

**Comment by codygman** [comment]
Isn't the plan to import these modules qualified?

So they would be like `Name.toText` which is objectively better than `Name.nameToText`. 

Even if we aren't going the qualified route I'd argue it's redundant to have the type you currently have in the name since you know what that type is.

When you use `nameToText` for instance you know your type is name and you want text.

I can see an argument for `nameToText` when reading code, but for me a lot of them composed together somehow become less readable.

Really though, this makes me want the coerce based solution we discussed even more.

**Comment by tfausak** [comment]
I'm arguing in favor of keeping `Name.fromText` and `Name.toText`. What I want to do is rename or remove `Prolude.fromText` and `Prolude.toText` because they collide with the functions we want to write. The problem is more apparent if you try to implement `Name.fromString`:

``` hs
fromString :: String -> Name
fromString = Name.fromText . Prolude.toText
```

Note that both identifiers need to be qualified because they're both ambiguous.
